[package]
name = "weird-xss"
version = "0.1.0"
authors = ["Daniel Pagan <dpagan@ibm.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "1.0"
actix-files = "0.1.5"
serde = "1.0.101"
